### ISSUE TITLE
Simplify and explain parse_xtal and parse_fragalysis

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#183]
Although these functions (in data.fragalysis) mostly do what they are meant to do, they are very hard to understand. They should be simplified and explained.

https://github.com/choderalab/asapdiscovery/pull/104/files#r1134677432

# TODO
- [ ] add full documentation and comments explaining the mechanics of the function
- [ ] change script to be more flexible and obvious as to what its doing
- [ ] raise Exception if no files are found instead of just using an assertion error
- [ ] After changing api, fix implementation in all uses

**Comment by hmacdope** [comment]
Wontfix now as we have moved to newer API
