### ISSUE TITLE
Standardize data labels to make them common and useful across projects and datasets

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#27]
Currently we have Fragalysis, SARS-redocked, and MERS-redocked datasets, from which we'd like to pull similar sets of information. I would like to organize the kind of information we are manipulating with so that we don't have annoying discrepancies that we have to deal with when we want to analyze different datasets (like "COMPOUND ID" vs "Compound_ID" vs "SARS_ligand" that all refer to the same thing).

# The Basics:
These items are true independent of how the complex was generated. 
- `Complex ID`: the name of the docked ligand+protein structure. Should be unique (i.e. more than just composed of the Compound and Protein IDs or even just the source IDs.
- `Compound ID`: the name of the compound in the structure
- `Protein ID`: the name of the protein / variant in the structure
- `SMILES`: smiles string of compound

## bonus: probably not necessary for our purposes but potentially useful to keep track of.
- `SEQRES`: sequence of protein in complex

# Sources
These depend on where the Compound and Protein structures were pulled from. 
- `Compound Source`: Usually will be the ID of a particular structure in the Fragalysis dataset with the `Compound ID` of this `Complex ID`
- `Structure Source`: Right now this can either be the ID of a Fragalysis structure OR a PDB ID.

# Information about the Complex structure:
## Generated by the MCSS / docking method
- `MCSS Rank`: this is a relative thing and dependent on the datasets used, so it will be necessary to make obvious exactly what was compared. Usually we calculate the MCSS of `Compound ID` to all the compounds in a set of `Structure Source` structures.
- `Chemgauss4`: generated by docking method
- `POSIT`: generated by docking method

## Stuff we can calculate after generating the dataset:
- RMSD (usually from `Compound ID` in `Structure ID` to `Compound ID` in `Reference ID`)

## Experimental Information
- IC50 (this will be empty a lot)

# Additional Definitions:
- `Design Unit`: a particular combination of protein and ligand coordinates; an input to docking or design. multiple `Complex ID`s can be generated from a single `Design Unit` depending on the docking protocol, etc.

# TODO
- [ ] make a global variable in the "docking" (or maybe data) submodule that has a version of all these tags
- [ ] implement the use of this global variable in all of the scripts that generate or process data

# Notes from #92 
## Description
It would be nice to have the DockingResults class be entirely in charge of adding and processing labels. I started working on this but am not sure I know the best way of doing this.

## Some goals:
- clarity about what the column is and what it is used for (i.e. I think Structure_Source or Protein_Source or Receptor_Source is better than i.e. "Structure" as it tells you that this is the location of the structure used as the input. Maybe standardizing the columns with Input_, Output_ and Score_ tags i.e. would be good as well
- accessible as DataFrame attributes using Pandas, i.e. df.Docked_File as opposed to df["Docked File"]
- easily converted into plot titles / axis labels / etc with a certain level of professionalism (i.e. upper-case instead of lower case)
- some way of keeping backwards compatibility, or versioning to avoid needing to re-write custom scripts and stuff

## TODO
- [ ] create a basic syntax for adding column labels that allows for different options
- [ ] add a more robust loading / save syntax for docking results
- [ ]  add some kind of versioning
- [ ]  convert all old scripts to use this new protocol

**Comment by mikemhenry** [comment]
[Internal link, but this is where we are documenting what we decide](https://www.notion.so/asapdiscovery/ASAP-Computational-Chemistry-SD-Tag-naming-conventions-71adb94230b2418caf5f900f9312d933)

**Comment by hmacdope** [comment]
This has been done in `docking_data_validation` and `manifold_data_validation` modules.
