### ISSUE TITLE
Re-do SARS fragalysis re-docking experiment

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#57]
Several improvements have been made to the docking protocol since the SARS re-docking experiment was first done

# To-Do
- [x] re-do SARS re-docking experiment
- [x] #111
- [x] consider adjusting MCSS docking to use Tanimoto coefficient instead of number of atoms
- [x] re-run simple docking
- [x] re-run docking with omega and clash options added
- [x] investigate some of the failures

# Scientific Questions to Answer
- [x] which scoring function does the best job (measured by AUC-ROC)? Where 'true positives' are compound docked to a pose within 2Å of the original structure
