### ISSUE TITLE
Missing deps for Conda Forge meta issue 

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#738]
We are looking to make the package conda-forge installable. 

To do this we will need to move all dependencies to conda-forge.

- [x]  pygifsicle https://pypi.org/project/pygifsicle/
- [x] airium https://pypi.org/project/airium/
- [x] logomaker https://pypi.org/project/logomaker/
- [x] cinnabar (this has a CF release but we are currently pip installing from `main` I think due to versioning things. @jthorton to confirm (perhaps 0.4.1 patch fixed this) EDIT: testing in #740

**Comment by hmacdope** [comment]
We also need to fix our pydantic pin #739

**Comment by hmacdope** [comment]
Airium WIP here: https://github.com/conda-forge/staged-recipes/pull/25012

**Comment by hmacdope** [comment]
Pygifsicle WIP here: https://github.com/conda-forge/staged-recipes/pull/25013

**Comment by hmacdope** [comment]
logomaker WIP here: https://github.com/conda-forge/staged-recipes/pull/25014

**Comment by hmacdope** [comment]
All deps are now on CF
