### ISSUE TITLE
Issues with generated models for downstream processing

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#75]
# Intro
The outputs of this need to conform to certain standards for downstream modeling. Currently some of these issues are in different issues on GitHub and I'd like to put them all together here

# To-Do
- [x] #73 
- [x] Ensure ligands are written out as HETATMs
- [x] Fix this TER card issue (not sure if it is really a problem, so first need to check if it is)
    - EDIT 2022.12.08 this is correct-looking as per the PDB docs: https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html
<img width="558" alt="image" src="https://user-images.githubusercontent.com/31800806/196522356-6a74fd44-60e7-4706-b80f-3280267b8c36.png">

- [x] #72 
- [x] #66 
- [x] determine what to do with the chain ID for the ligand (also in #73)
- [x] determine if SDF files should have explicit or implicit hydrogens currently in #65 
    - I am keeping them. previously we had been manually deleting them but there is probably a way to keep them as implicit.
- [x] create a DesignUnit-saving API that does all of this stuff! currently this is done in `fauxalysis_from_docking.py` in #65 but I think it would be better if it lived outside of a script
    - this is now done in `data.openeye.save_openeye_design_unit`
